### ISSUE TITLE
teach us how to do good technical drawings 

### ISSUE THREAD

**Issue by jurra** [goscommons/goscommons.github.io#12]
We are looking for someone with expertise in CAD drawing who can teach us best practices and give us n introduction to documentations standards.

**Comment by polemidis** [comment]
Not an expert, but Freecad has a new workbench called TechDraw which has good reviews, and is officially supported. It replaced the buggy drawing workbench they use to have

**Comment by jurra** [comment]
I was checking it out yeah! Works pretty good

**Comment by JannesHN** [comment]
I had to learn these norms from a book in my studies, about 7 years ago. Never properly used it and so forgot it again. I'm looking through my old books again.

**Comment by jurra** [comment]
Great jannes this will help a lot :smile:

**Comment by jurra** [comment]
I found an interesting blog by an expert guy in technical drawing standards, send him a tweet but no response yet. Very interesting blog check it out:  https://cadsetterout.com/technical-drawing-standards/

**Comment by jurra** [comment]
@JannesHN I had the same problem, I studied those, but never really understood the meaning and the application of such drawings. There are different ways of doing drawings, depending on what is the goal, either to discuss about possible designs, or document a part that is ready to deliver for a manufacturer
