### ISSUE TITLE
Redesign of our jekyll website

### ISSUE THREAD

**Issue by goscommons** [goscommons/goscommons.github.io#14]
Hi there we are currently working with a jekyll theme, and currently we are developing a new redesign first of a simple front page. If you want to practice your scrum, design, git and dev skills this is a good place to start doing it :smile: 

## These are a couple of steps to join the task:
0. Clone this repository so that you can contribute to it.
1. We build together as a team a product backlog of the features that are more important.
2. We make a break down of tasks to work on.
3. We prioritize the tasks based on milestones and goals we want to achieve.
4. We start designing, prototyping and testing them, step by step. 
5. We release a new version based on our goals and milestones :1st_place_medal:

**Comment by jurra** [comment]
Current version is not done with jekyll but only html.
