### ISSUE TITLE
TU Delft : May 9th, Open Design Hackathon focused on home appliances

### ISSUE THREAD

**Issue by goscommons** [goscommons/goscommons.github.io#5]
## We are running two different events, one physical at TU Delft the 9th of May. We will be also available for the Global sprint of Mozilla running 10th, and 11th of May, from 9:00 to 17:00, CEST timezone.
Welcome to the GO!Commons repo and initiative. In the last 10 weeks we have been coached by the Mozilla Open Leaders (Awesome)Program, to learn how to work open and become better impact makers. We are a group of designers and engineers interested in Open Source and Sustainable Development. We are part of a network of communities and organizations that have amazing experience in open source. We are also inspired by amazing initiatives like [Open Source Ecology](https://www.opensourceecology.org/), [Precious Plastics](https://preciousplastic.com/), [RepRap](http://reprap.org/wiki/RepRap), [Open Source Circular Economy days](https://oscedays.org/) and many others.

## 1. How to participate and prepare for the hackathon? <a name="how_to"></a>
- [x] [**See our Sprint Hackathon Board**](https://github.com/goscommons/goscommons.github.io/projects/3) to get an idea of how we will work using a Kanban/ Scrum/ Agile board.
- [x] Read the documentation below and get an idea of what this is about.
- [x] Make a github account and mention below in the comments you would like to participate. You can also mention your background so that we can orient and facilitate better your contribution. We will also help you in using the command line.
- [x] We will be from 13:30 to 18:00 in the Norbert Rosenburg room at the faculty of Industrial Design in Delft, official time to start is 14:30.
- [x] Let us know also what questions or thoughts you have about the project and the event.

## What is this hackathon about?
We will focus on documenting designs of consumer goods like washing machines, dryers, microwaves, etc.  _Is the topic or theme of the hackathon if you like_ . [Check this video to see why this theme is so relevant](https://youtu.be/a0ZlbdXBNc0)
### What will happen in the hackathon?
We want to get inspiration from you, and hopefully you will get inspired this day. We also want you to get out of the session, with some collaborative tools on your pocket like git and github. We will work on a case study: a vacuum cleaner. We will disassemble one vacuum cleaner, study and document its design together.
![goc1_disassembly](https://user-images.githubusercontent.com/39052270/39759761-cac7e70c-52d3-11e8-90d9-c070fb2989fb.jpg)

#### By the end of this event you will:
1. Learn the value of open design and its proper documentation.
2. Collaborate in an open design documentation exercise and learn github in this process.
3. Get an idea of how to use open licenses and why they are important.
4. Hopefully join our open design community and become a contributor.
5. You will get our awesome e-Book on p2p, open source and sustainable development.

### The impact of having open design documentation
> The impact of this project is multifaceted, and has advantages from all kinds of aspects from practical and industrial, to intellectual and spiritual. Think of it as a common resource that facilitates sustainability in many ways.

* Students and hobbyists can become highly skilled designers, makers, engineers and facilitators by joining as contributors to the community.
* Designs can be more universal, modular and standardize so that repair is facilitated, quality guaranteed and eventually lead to ecofriendliness.
* Manufacturers and entrepreneurs can share and use their contributions under open licenses
* Can you think of other advantages?

## Who is it for?
* Anyone interested and willing to participate in developing common industrial design resources for the benefit of all.  
* Anyone interested in learning from others by working in collaborative decentralized processes.
* Anyone interested in teaching and bringing their core expertise to make this happen in the context of highly concurred and collaborative processes. You could be a technologist, designer, illustrator, marketer, project manager, among other many roles.

## How the open design repositories work:
To have a clear idea of our collaborative workflow see [our contributing guidelines](https://goscommons/goscommons.github.io/CONTRIBUTING.md).
But basically interactions take place in specific open design repositories. Follow the issues which are basically tasks posted for people like you to take over and return a valuable increment to the design repository. For instance if you [go to the issues section of the open source microwave](https://github.com/goscommons/goscommons.github.io/issues), repo you will see tasks, but you can also propose new tasks.

The designs documented can be your own version of a machine or a module, but also could be existing versions. These way people can see how things work, and also how professionals work collaboratively.
Making our repo open for the public allows that any person can study, and learn from others by doing and seeing others doing.

**Comment by JornR94** [comment]
Would love to join!

**Comment by Soonali** [comment]
I will be there :)

**Comment by JorisBlok** [comment]
Count me in!

**Comment by johanvanderschaaf** [comment]
Super exciting, I'm in!

**Comment by goscommons** [comment]
Great! we are also super excited and happy that you are joining! The documentation in this issue has been updated, since w accidentally deleted the participation guidelines. Now you can see the [Sprint board for the hackathon](https://github.com/goscommons/goscommons.github.io/projects/3) with the issues updated. This will give you an idea of what will happen :sparkles:

**Comment by Toosje** [comment]
I love open source, I'm in! This is so up my street, I want to empower individuals and small businesses to contribute to- and benefit from open source design! Information wants to be free!

**Comment by jurra** [comment]
I agree @Toosje! we are very much into what you are saying and share same feelings!

**Comment by designswarm** [comment]
Check out iotmark.org and https://github.com/openiotmark/ which might tie in with what you guys are doing!

**Comment by krishnarajagopal2011** [comment]
I am in too. I am very interested in open source movement that too in the hardware sense, for the benefit of all. Really excited to be part of it.

**Comment by jurra** [comment]
Hi guys. We also created a chat room on gitter to start talking, pre-during-post hackathon. Mainly for pre and post-hackathon. There are many interesting topics and nice things to talk about. But also it can be very helpful in case you are interested in collaborating also after the hackathon, 
## [This is the gitter chat, feel free to join from today](https://gitter.im/goscommons-github-io/May-nineth-hackathon?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by goscommons** [comment]
## Good morning everyone :sparkle: :sparkle: 
[Here is the link to the book and the presentation slides](https://github.com/goscommons/goscommons.github.io/tree/master/materials)

For those interested in learning more about open source and continuing with us the journey [join the chat room.](https://gitter.im/goscommons-github-io/10th-11th-May-Mozilla-Hackathon?utm_source=share-link&utm_medium=link&utm_campaign=share-link) If you are interested in feeling how an open global sprint organized by Mozilla works, this is a great opportunity. Hope to see you around, and keep getting better in open design.

**Comment by jurra** [comment]
##  :sparkles: What we learned from the sprint and your feedback :small_airplane: 

##Hi! We have received feedback from you and your impression of the workshop. 

Great that most of you liked it very much and learned something. **We also learned a lot thanks to your enthusiasm and constructive criticisms.**  This is our first workshop of this kind, and we felt you supported us as well in the session.

### Based on your comments we have reflected on what will be done better for new sessions.

- The one and most important, is to start right away with proper application to manage git. Although we shared it in the instructions, we ended up in the command line, which can be scary for many.

- We think this introductory session, is a good start to learn open source practices, as well as agile management and development. But more practice is needed to get good at it and enjoy it. So we will open the possibility of supporting and continuing teaching whom ever is interested developing this skills.

- We will try to make even more explicit the sustainability dimension, since it was discussed in the morning presentation, but it was not added in the retrospective of the afternoon session.

### Thank you very much! hoping to see you soon :smile_cat:
