### ISSUE TITLE
Mozilla Global Sprint 2018-May 10th & 11th Virtual Hackathon

### ISSUE THREAD

**Issue by goscommons** [goscommons/goscommons.github.io#6]
![open-design-sprint-virtual-07-07](https://user-images.githubusercontent.com/18581201/39005148-a6213fe4-43ff-11e8-9dfa-f6e54fc91900.png)
# Table of Contents
1. [How to participate](#how_to)
2. [About the GO!Commons and Mozilla Foundation](#about)
3. [What will happen in the hackathon](#what_happens)
4. [What you will learn](#to_learn)
5. [How it works](#how_it_works)
6. [The impact of having open design documentation](#the_impact_of_open)

We are running two different events, one physical at TU Delft the 9th of May. We will be also available for the Global sprint of Mozilla running 10th, and 11th of May, from 9:00 to 17:00, CEST timezone.

## 1. How to participate? <a name="how_to"></a>
- [ ] **[Join our public chat room](https://gitter.im/goscommons-github-io/10th-11th-May-Mozilla-Hackathon) for this event so that we can meet and collaborate better.**
- [ ] Make a github account and mention below in the comments you would like to participate. You can also mention your background so that we can orient and facilitate better your contribution.
- [ ] [**See our Sprint Hackathon Board**](https://github.com/goscommons/goscommons.github.io/projects/2) to get an idea of how we will work using a Kanban/ Scrum/ Agile board.
- [ ] There is also a [**video conference room**](https://zoom.us/j/758482712?pwd=) available to have face to face talk once we have participants in the chat room.
- [ ] We will be available 10th and 11th of May from 9:00 am to 5:00pm on CEST timezone. Make sure you can also make it during that time if you want to be supported virtually by us.

 [See Mozilla Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/)
## 2. About the GO!Commons and Mozilla Foundation <a name="about"></a>
Welcome to the GO!Commons repo and initiative. In the last 10 weeks we have been coached by the Mozilla Open Leaders (Awesome)Program, to learn how to work open and become better impact makers. We are a group of designers and engineers interested in Open Source and Sustainable Development. We are part of a network of communities and organizations that have amazing experience in open source. We are also inspired by amazing initiatives like [Open Source Ecology](https://www.opensourceecology.org/), [Precious Plastics](https://preciousplastic.com/), [RepRap](http://reprap.org/wiki/RepRap), [Open Source Circular Economy days](https://oscedays.org/) and many others.

## 3. What will happen in the hackathon? <a name="what_happens"></a>
We have been focusing on documenting designs of consumer goods like washing machines, dryers, microwaves, etc. [Check this video to see why this theme is so relevant](https://youtu.be/a0ZlbdXBNc0). But the call is open for other equipment as well. If you have an equipment that you want to document leave a message to prepare before the hackathon.

We want to get inspiration from you, and hopefully you will get inspired this day. We also want you to get out of the session, with some collaborative tools on your pocket like git and github.

## 4 By the end of this event you will: <a name="to_learn"></a>
1. Learn the value of open design and its proper documentation.
2. Collaborate in an open design documentation exercise and learn github in this process.
3. Get an idea of how to use open licenses and why they are important.
4. Hopefully join our open design community and become a contributor.
5. You will get our awesome e-Book on p2p, open source and sustainable development.

## 5. How it works <a name="how_it_works"></a>
We basically host a set of design repositories. You will learn how to contribute around issues that are specific to a repository or project. There are tasks for people with different backgrounds (from documenting in the Wiki, to CAD Modeling, leading new repos, etc). If you feel you would like to open a new work item, let us know via the comments. We will assist you the best we can online during these days.

To have a clear idea of our collaborative workflow see [our contributing guidelines](https://goscommons/goscommons.github.io/CONTRIBUTING.md).
But basically interactions take place in specific open design repositories. Follow the issues which are basically tasks posted for people like you to take over and return a valuable increment to the design repository. For instance if you [go to the issues section of the open source microwave](https://github.com/goscommons/goscommons.github.io/issues), repo you will see tasks, but you can also propose new tasks.

The designs documented can be your own version of a machine or a module, but also could be existing versions. These way people can see how things work, and also how professionals work collaboratively.
Making our repo open for the public allows that any person can study, and learn from others by doing and seeing others doing.

## 6. The impact of having open design documentation <a name="the_impact_of_open"></a>
> The impact of this project is multifaceted, and has advantages from all kinds of aspects from practical and industrial, to intellectual and spiritual. Think of it as a common resource that facilitates sustainability in many ways.

* Students and hobbyists can become highly skilled designers, makers, engineers and facilitators by joining as contributors to the community.
* Designs can be more universal, modular and standardize so that repair is facilitated, quality guaranteed and eventually lead to ecofriendliness.
* Manufacturers and entrepreneurs can share and use their contributions under open licenses
* Can you think of other advantages?

### Who is it for?
* Anyone interested and willing to participate in developing common industrial design resources for the benefit of all.  
* Anyone interested in learning from others by working in collaborative decentralized processes.
* Anyone interested in teaching and bringing their core expertise to make this happen in the context of highly concurred and collaborative processes. You could be a technologist, designer, illustrator, marketer, project manager, among other many roles.

**Comment by polemidis** [comment]
I will read it in more detail later, but in general I liked it. Big difference! Until I finish my machines I will not be able to contribute nowhere else, but at least all my research will not be wasted. The grapple is 100% done, i had input from professional fabricator, it just needs documentation, the plasma cad is almost done, it needs correction on errors. The plasma CNC cutter will open a lot of doors in machine fabrication! Both machines have no obstacles to overcome, all the problems are solved. I am so excited!!!

**Comment by jurra** [comment]
Great @polemidis! with this project we are basically creating an open design documentation standard. This will help you not only to document your results, but also your process. We will talk about how to use the "issues" in GitHub to delegate and decentralize tasks in an asynchronous and way. For the other members and friends of the community, @polemidis is a friend I met at open source ecology. He was a major contributor and inspiration for me to also contribute and learn! He is a farmer and a maker, he has design machines to use in his farm and has a lot of experience. I am also very excited about what he is doing!

**Comment by memeco** [comment]
I want to participate too! 

I'm a Brazilian sociologist and civic hacker, I'm also doing a masters about Civic Hackers in São Paulo, Brazil.

Oh, I'm also very knowledgeable about BitTorrent and I'm an admin of a big private tracker called Waffles. For invites just send me a message. ;)

Looking forward for more Git and Collaborative workflows.

**Comment by jurra** [comment]
Hi Emerson!! Great to have you joining!! This is Jose from Cuba
We have you already onboard!! Do you have already a github account?

Best regards,

Jose

**Comment by jurra** [comment]
If you also know others interested,
from different disciplines like engineering, design, etc. you can also
invite them

**Comment by CharleyQuinton** [comment]
Openness and togetherness is the future. Ideas and original thought cannot be 'property' nor can 'exclusive rights' continue to thwart human progress. This initiative is right on time.

**Comment by jurra** [comment]
Charley dot you also want to join?
Regards,

Jose

**Comment by feferri** [comment]
I'm in

**Comment by goscommons** [comment]
Hi @feferri welcome!

**Comment by jurra** [comment]
## Check the participants guidelines officially posted by Mozzilla >>> [Participatns guide](https://mozilla.github.io/global-sprint/participants-guide/)
We have to add also other roles, and skills needed:

> As a participant at the Global Sprint, you might:
add your own unique perspective by advising on project ideas and plans
> - help with research for content, UX or design
> - create graphics and logos, or design layouts and mock-ups
> - help with QA (quality assurance) testing on prototype tools or apps
> - contribute code in a variety of languages, from HTML to C++
> - write or edit project content like instructions, descriptions and documentation,
> - and much more… see our list of “help wanted” categories to find a match for your skills
> Participants should be aware that their contributions to projects during the Sprint will fall under each project’s own license, and may be be reused, remixed, and shared according to that license.

Since we are working on design and open hardware project we have extended the participants guide: 
**Engineering skills of any domain:** mechanical engineering, software engineering, electronic and electrical engineering, also testers.

**Leadership, design and project management skills:** this involves entrepreneurial background, but also communication skills, scrum and agile backgrounds.

**Activist and event organizing skills:** we need people that know how to run campaigns, use social media and is able as well to organize and run events.

**Comment by urrape** [comment]
Hi! Specially interested "in learning from others by working in collaborative decentralized processes"

**Comment by vinaybhajantri** [comment]
Hey all, I'm currently working on the tractor CAD model, trying to replicate the Chalmers G model (based on expired patent). Will be updating the sprint board soon.

**Comment by jurra** [comment]
Wow we got another champion @vinaybhajantri Awesome move!!!
